services:
  - type: web
    name: attendance-portal-v2
    runtime: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn --chdir school-portal/backend --timeout ${GUNICORN_TIMEOUT:-900} app:app"
    envVars:
      - key: MONGO_DB_NAME
        value: attendance_db
      - key: FLASK_DEBUG
        value: "False"
      - key: MONGO_URI
        sync: false
